# --- Build Stage ---
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Install dependencies for build
RUN apk add --no-cache git

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build binary
RUN go build -o ecommerce-backend ./cmd/api

# --- Run Stage ---
FROM alpine:3.19

WORKDIR /app

# Install CA certificates (for HTTPS)
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/ecommerce-backend .
COPY config.yaml .    # Copy config if you want default dev config inside container

EXPOSE 8080

CMD ["./ecommerce-backend"]
